name: Upload Debug Symbols

on:
  workflow_dispatch: # manual trigger only
  push:
    branches: [ main ]
    paths:
      - 'Plugins/Sentry/**'
      - 'Source/**'
      - '.github/workflows/upload-symbols.yml'

env:
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

jobs:
  upload-symbols:
    name: Upload Debug Symbols
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install sentry-cli
        run: |
          pip install sentry-cli

      - name: Upload debug symbols (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          ./scripts/upload-debug-symbols.sh

      - name: Upload debug symbols (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Upload game debug symbols
          if (Test-Path "Builds\Windows\SentryTower.exe") {
            sentry-cli debug-files upload `
              --org="$env:SENTRY_ORG" `
              --project="$env:SENTRY_PROJECT" `
              --auth-token="$env:SENTRY_AUTH_TOKEN" `
              --include-sources `
              "Builds\Windows\SentryTower.exe" `
              "Builds\Windows\SentryTower.pdb"
          }
          
          # Upload plugin debug symbols
          if (Test-Path "Plugins\Sentry\Binaries\Win64\UnrealEditor-Sentry.dll") {
            sentry-cli debug-files upload `
              --org="$env:SENTRY_ORG" `
              --project="$env:SENTRY_PROJECT" `
              --auth-token="$env:SENTRY_AUTH_TOKEN" `
              --include-sources `
              "Plugins\Sentry\Binaries\Win64\UnrealEditor-Sentry.dll" `
              "Plugins\Sentry\Binaries\Win64\UnrealEditor-SentryEditor.dll"
          } 